{% set name = "pandoc-plot" %}
{% set version = "1.0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LaurentRDC/{{ name }}/releases/download/{{ version }}/pandoc-plot-windows-x86_64.zip  # [win]
  sha256: 2697b67cd8a0c0007961c3e0e5893799f7b77d83d95b406581559595789651de  # [win]

  url: https://github.com/LaurentRDC/{{ name }}/releases/download/{{ version }}/pandoc-plot-linux-x86_64-static.tar.xz  # [linux64]
  sha256: dc07b36f9445233b2389d8be6ff48532ff7f9ed225065c7c6e6f2fae5b19d6c9  # [linux64]

  url: https://github.com/LaurentRDC/{{ name }}/releases/download/{{ version }}/pandoc-plot-macos-x86_64.tar.xz  # [osx]
  sha256: a680156b84f0cae782a4e79b535c33b4279c043374635fe2fddcaf95de7fa9ae  # [osx]

build:
  number: 0

requirements:
  run:
    - pandoc >=2.11,<2.12

test:
  commands:
    - pandoc-plot --version
    - pandoc-plot --help

about:
  home: https://github.com/LaurentRDC/pandoc-plot
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Render and include figures in Pandoc documents using your plotting toolkit of choice
  description: |
    pandoc-plot turns code blocks present in your documents (Markdown, LaTeX, etc.) 
    into embedded figures, using your plotting toolkit of choice, including Matplotlib, ggplot2, 
    MATLAB, Mathematica, and more.
  doc_url: https://github.com/LaurentRDC/pandoc-plot/
  dev_url: https://github.com/LaurentRDC/pandoc-plot/

extra:
  recipe-maintainers:
    - LaurentRDC
