{% set name = "pandoc-plot" %}
{% set version = "0.7.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LaurentRDC/{{ name }}/releases/download/{{ version }}/pandoc-plot-windows-x86_64.zip  # [win]
  sha256: 3880af69f233ad4c9c8a97f9a8c910c23b23ecd0d05628eeaf9700e70d31cd0c  # [win]

  url: https://github.com/LaurentRDC/{{ name }}/releases/download/{{ version }}/pandoc-plot-macos-x86_64.tar.xz  # [osx]
  sha256: 0d2549565ee4020160b41c9baab0bac4f44a159a58bc116eec552ead8251d3e5  # [osx]

build:
  skip: true  # [linux]
  number: 0

requirements:
  run:
    - pandoc >=2.10

test:
  commands:
    - pandoc-plot --version
    - pandoc-plot --help

about:
  home: https://github.com/LaurentRDC/pandoc-plot
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Render and include figures in Pandoc documents using your plotting toolkit of choice
  description: |
    pandoc-plot turns code blocks present in your documents (Markdown, LaTeX, etc.) 
    into embedded figures, using your plotting toolkit of choice, including Matplotlib, ggplot2, 
    MATLAB, Mathematica, and more.
  doc_url: https://github.com/LaurentRDC/pandoc-plot/
  dev_url: https://github.com/LaurentRDC/pandoc-plot/

extra:
  recipe-maintainers:
    - LaurentRDC
