{% set name = "pandoc-plot" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LaurentRDC/{{ name }}/releases/download/{{ version }}/pandoc-plot-Windows-x86_64.zip  # [win]
  sha256: 2b592b3677e974dd59fbf94a3199473bb142241142eb861a67eb61e060f8a46e  # [win]

  url: https://github.com/LaurentRDC/{{ name }}/releases/download/{{ version }}/pandoc-plot-Linux-x86_64-static.zip  # [linux64]
  sha256: 000e412170d225bf12cfd78936916147ee85aa2b4081c016432610c4a73d7081  # [linux64]

  url: https://github.com/LaurentRDC/{{ name }}/releases/download/{{ version }}/pandoc-plot-macOS-x86_64.zip  # [osx]
  sha256: f278c6ef915b55609f558626c4ca845406c7c58f041ba348780b7114c006072c  # [osx]

build:
  number: 0

requirements:
  run:
    - pandoc >=2.11,<2.15

test:
  commands:
    - pandoc-plot --version
    - pandoc-plot --help

about:
  home: https://github.com/LaurentRDC/pandoc-plot
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Render and include figures in Pandoc documents using your plotting toolkit of choice
  description: |
    pandoc-plot turns code blocks present in your documents (Markdown, LaTeX, etc.) 
    into embedded figures, using your plotting toolkit of choice, including Matplotlib, ggplot2, 
    MATLAB, Mathematica, and more.
  doc_url: https://github.com/LaurentRDC/pandoc-plot/
  dev_url: https://github.com/LaurentRDC/pandoc-plot/

extra:
  recipe-maintainers:
    - LaurentRDC
