{% set version = "1.2.3" %}

package:
  name: pandoc-plot
  version: {{ version }}

source:
  url: https://github.com/LaurentRDC/pandoc-plot/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6f2361e69e365f5614b7579b4f3a91288956da15a0d6042d91c665916beadd91
build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]
    - {{ compiler('cxx') }}
    - stack >=2.7.1,<3
  host:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]
    - {{ compiler('cxx') }}
    - stack >=2.7.1,<3
  run:
    - pandoc >=2.11,<2.15

test:
  commands:
    - pandoc-plot --version
    - pandoc-plot --help

about:
  home: https://github.com/LaurentRDC/pandoc-plot
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Render and include figures in Pandoc documents using your plotting toolkit of choice
  description: |
    pandoc-plot turns code blocks present in your documents (Markdown, LaTeX, etc.) 
    into embedded figures, using your plotting toolkit of choice, including Matplotlib, ggplot2, 
    MATLAB, Mathematica, and more.
  doc_url: https://github.com/LaurentRDC/pandoc-plot/
  dev_url: https://github.com/LaurentRDC/pandoc-plot/

extra:
  recipe-maintainers:
    - LaurentRDC
